### ISSUE TITLE
Trouble Using the App

### ISSUE THREAD

**Issue by fbruzzaniti** [daveherrald/SA_plaso-app-for-splunk#1]
I was able to install the Splunk App easily enough, but I'm not sure the procedure I should use to add and view the timeline.  I imported my log2timeline .csv into Splunk as Source Type .csv. From here I'm stuck I'm not sure how to get the timeline to show up on the dashboard in Splunk.  

Also is the defaul .csv Source Type ok because I noticed it adds it's own time "_time" instead if using the "time" column. Do I need to define a new SourceType for log2timeline or change the column used for time, or just leave it as the defaukts for .csv Source Type.

**Comment by daveherrald** [comment]
Check this out: https://vimeo.com/197568364
